version: '2.1'
orbs: 
  ecr-ecs: dsi/ecr-ecs@3.0.1
workflows:
  build-and-deploy:
    jobs:
      - ecr-ecs/upload-deploy:
          app_name: "trey_node_api"
          aws-region: AWS_DEFAULT_REGION
        
# version: '2.1'
# orbs: 
#   aws-ecr: circleci/aws-ecr@7.3.0
#   aws-ecs: circleci/aws-ecs@02.2.1
# workflows:
#   build_and_push_image:
#     jobs:
#       - aws-ecr/build-and-push-image:
#           account-url: AWS_ECR_ACCOUNT_URL
#           aws-access-key-id: AWS_ACCESS_KEY_ID
#           aws-secret-access-key: AWS_SECRET_ACCESS_KEY
#           create-repo: true
#           dockerfile: Dockerfile
#           path: .
#           profile-name: default
#           region: AWS_DEFAULT_REGION
#           repo: trey_node_api
#           tag: "latest,$CIRCLE_SHA1"
